import { HttpClient } from '@angular/common/http';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { environment } from '../../../../environments/environment';
import { Invoice, InvoiceCreateRequest, InvoiceItem, InvoiceItemRequest, InvoiceStatus } from '../../../core/models';
import { AuthService } from '../../../core/services/auth.service';
import { ApiService, PagedResponse } from '../../../core/services/api.service';

@Component({
  selector: 'app-invoices',
  template: `
    <div class="page-container">
      <div class="page-header">
        <div>
          <h1>Invoices</h1>
          <p>Track automated billing, payment status, and manual invoice updates from the live backend.</p>
        </div>

        <div class="header-actions">
          <button class="btn-secondary" type="button" (click)="loadInvoices(true)">
            Refresh
          </button>
          <button
            *appHasPermission="'Invoices'; appHasPermissionAction: 'Create'"
            class="btn-primary"
            type="button"
            (click)="openCreateForm()">
            Create Invoice
          </button>
        </div>
      </div>

      <div class="status-message info" *ngIf="actionMessage">{{ actionMessage }}</div>
      <div class="status-message success" *ngIf="successMessage">{{ successMessage }}</div>
      <div class="status-message error" *ngIf="errorMessage">{{ errorMessage }}</div>

      <div class="summary-grid">
        <app-stat-card label="Total Invoices" [value]="allInvoices.length" icon="IN"></app-stat-card>
        <app-stat-card label="Pending" [value]="countByStatus('Pending')" icon="PD"></app-stat-card>
        <app-stat-card label="Paid" [value]="countByStatus('Paid')" icon="PA"></app-stat-card>
        <app-stat-card label="Overdue" [value]="countByStatus('Overdue')" icon="OD"></app-stat-card>
        <app-stat-card label="Auto Generated" [value]="autoGeneratedCount" icon="AG"></app-stat-card>
      </div>

      <div class="summary-note" *ngIf="allInvoices.length > 0">
        <span>Outstanding total: {{ totalOutstanding | number:'1.2-2' }}</span>
        <span>Auto-refresh: every 15 seconds</span>
      </div>

      <div class="toolbar">
        <select [(ngModel)]="statusFilter">
          <option value="">All Statuses</option>
          <option value="Pending">Pending</option>
          <option value="Partial">Partial</option>
          <option value="Paid">Paid</option>
          <option value="Cancelled">Cancelled</option>
          <option value="Overdue">Overdue</option>
        </select>
      </div>

      <section class="form-shell" *ngIf="isFormOpen">
        <h2>{{ isEditMode ? 'Edit Invoice' : 'Create Invoice' }}</h2>

        <form [formGroup]="invoiceForm" (ngSubmit)="saveInvoice()">
          <div class="form-grid">
            <div class="form-group">
              <label>Customer Id</label>
              <input type="number" formControlName="customerId">
            </div>
            <div class="form-group">
              <label>Service Request Id</label>
              <input type="number" formControlName="serviceRequestId">
            </div>
            <div class="form-group">
              <label>Invoice Date</label>
              <input type="date" formControlName="invoiceDate">
            </div>
            <div class="form-group">
              <label>Status</label>
              <select formControlName="status">
                <option value="Pending">Pending</option>
                <option value="Partial">Partial</option>
                <option value="Paid">Paid</option>
                <option value="Cancelled">Cancelled</option>
              </select>
            </div>
            <div class="form-group">
              <label>Tax Rate</label>
              <input type="number" min="0" step="0.01" formControlName="taxRate">
            </div>
          </div>

          <div class="items-section">
            <div class="items-header">
              <h3>Invoice Items</h3>
              <button type="button" class="btn-secondary" (click)="addItem()">Add Item</button>
            </div>

            <div formArrayName="items" class="items-grid">
              <div class="item-row" *ngFor="let item of itemControls; let index = index" [formGroupName]="index">
                <input type="text" placeholder="Item name" formControlName="itemName">
                <input type="number" min="1" placeholder="Qty" formControlName="quantity">
                <input type="number" min="0" step="0.01" placeholder="Unit price" formControlName="unitPrice">
                <button type="button" class="btn-link danger" (click)="removeItem(index)" [disabled]="itemControls.length === 1">
                  Remove
                </button>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <button class="btn-primary" type="submit" [disabled]="submittingForm">
              {{ submittingForm ? 'Saving...' : (isEditMode ? 'Save Invoice' : 'Create Invoice') }}
            </button>
            <button class="btn-secondary" type="button" [disabled]="submittingForm" (click)="closeForm()">Cancel</button>
          </div>
        </form>
      </section>

      <app-loading *ngIf="isLoading" message="Loading invoices..."></app-loading>

      <section class="table-shell" *ngIf="!isLoading">
        <app-empty-state
          *ngIf="visibleInvoices.length === 0"
          icon="[ ]"
          title="No invoices found"
          [message]="statusFilter ? 'No invoices matched the selected status.' : 'Invoices will appear here once records are created.'">
        </app-empty-state>

        <table *ngIf="visibleInvoices.length > 0">
          <thead>
            <tr>
              <th>Invoice No</th>
              <th>Request</th>
              <th>Customer</th>
              <th>Source</th>
              <th>Status</th>
              <th>Outstanding</th>
              <th>Total</th>
              <th>Date</th>
              <th *ngIf="showActionsColumn">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let invoice of visibleInvoices">
              <td>{{ invoice.invoiceNo }}</td>
              <td>{{ invoice.requestNo || ('SR #' + invoice.serviceRequestId) }}</td>
              <td>{{ invoice.customerName || ('Customer #' + invoice.customerId) }}</td>
              <td>
                <span class="source-chip" [class.auto]="invoice.autoGenerated">
                  {{ invoice.autoGenerated ? 'Auto' : 'Manual' }}
                </span>
              </td>
              <td><app-status-badge [status]="invoice.status"></app-status-badge></td>
              <td>{{ getOutstandingAmount(invoice) | number:'1.2-2' }}</td>
              <td>{{ invoice.totalAmount | number:'1.2-2' }}</td>
              <td>{{ invoice.invoiceDate | date:'mediumDate' }}</td>
              <td *ngIf="showActionsColumn" class="actions">
                <button
                  *appHasPermission="'Invoices'; appHasPermissionAction: 'Update'"
                  class="btn-link"
                  type="button"
                  (click)="editInvoice(invoice)">
                  Edit
                </button>
                <button
                  *appHasPermission="'Invoices'; appHasPermissionAction: 'Delete'"
                  class="btn-link danger"
                  type="button"
                  (click)="deleteInvoice(invoice)">
                  Delete
                </button>
                <button
                  *appHasPermission="'Invoices'; appHasPermissionAction: 'Export'"
                  class="btn-link"
                  type="button"
                  (click)="exportInvoice(invoice)">
                  Export
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </section>
    </div>
  `,
  styles: [`
    .page-container {
      padding: 2rem;
    }

    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
      gap: 1rem;
      margin-bottom: 1.5rem;
    }

    .page-header h1 {
      margin: 0 0 0.4rem;
    }

    .page-header p {
      margin: 0;
      color: var(--text-muted);
    }

    .header-actions {
      display: flex;
      gap: 0.75rem;
      flex-wrap: wrap;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: repeat(5, minmax(0, 1fr));
      gap: 1rem;
      margin-bottom: 1rem;
    }

    .summary-note {
      display: flex;
      justify-content: space-between;
      gap: 1rem;
      color: var(--text-muted);
      margin-bottom: 1rem;
      flex-wrap: wrap;
    }

    .toolbar {
      margin-bottom: 1rem;
    }

    .toolbar select {
      padding: 0.75rem 1rem;
      border: 1px solid var(--border-subtle);
      border-radius: 10px;
      background: var(--surface-solid);
    }

    .status-message {
      border-radius: 8px;
      padding: 0.9rem 1rem;
      margin-bottom: 1rem;
    }

    .status-message.info {
      background: var(--info-soft);
      color: var(--info);
      border: 1px solid var(--info-border);
    }

    .status-message.success {
      background: var(--success-soft);
      color: var(--success);
      border: 1px solid var(--success-border);
    }

    .status-message.error {
      background: var(--danger-soft);
      color: var(--danger);
      border: 1px solid var(--danger-border);
    }

    .btn-primary,
    .btn-secondary {
      border: none;
      border-radius: 10px;
      padding: 0.75rem 1.2rem;
      cursor: pointer;
      font-weight: 600;
    }

    .btn-primary {
      background: var(--primary);
      color: var(--text-light);
    }

    .btn-secondary {
      background: var(--surface-muted-strong);
      color: var(--text-dark);
    }

    .btn-link {
      border: none;
      background: none;
      color: var(--primary);
      cursor: pointer;
      padding: 0;
      font-weight: 600;
    }

    .btn-link.danger {
      color: var(--danger);
    }

    .form-shell,
    .table-shell {
      background: var(--surface-solid-strong);
      border-radius: 14px;
      padding: 1rem;
      box-shadow: var(--shadow-md);
      margin-bottom: 1.5rem;
    }

    .form-grid {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 1rem;
    }

    .form-group label {
      display: block;
      margin-bottom: 0.4rem;
      font-weight: 500;
    }

    .form-group input,
    .form-group select {
      width: 100%;
      padding: 0.75rem 0.85rem;
      border: 1px solid var(--border-subtle);
      border-radius: 10px;
      background: var(--surface-solid);
    }

    .items-section {
      margin-top: 1.25rem;
    }

    .items-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 1rem;
      margin-bottom: 1rem;
    }

    .items-grid {
      display: grid;
      gap: 0.75rem;
    }

    .item-row {
      display: grid;
      grid-template-columns: 2fr 1fr 1fr auto;
      gap: 0.75rem;
      align-items: center;
    }

    .item-row input {
      width: 100%;
      padding: 0.75rem 0.85rem;
      border: 1px solid var(--border-subtle);
      border-radius: 10px;
      background: var(--surface-solid);
    }

    .form-actions {
      display: flex;
      gap: 0.75rem;
      margin-top: 1.25rem;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    th,
    td {
      padding: 0.85rem 0.75rem;
      text-align: left;
      border-bottom: 1px solid var(--border-subtle);
    }

    th {
      background: var(--surface-muted);
      color: var(--text-body);
      font-weight: 600;
    }

    .actions {
      display: flex;
      gap: 0.75rem;
      flex-wrap: wrap;
    }

    .source-chip {
      display: inline-flex;
      align-items: center;
      padding: 0.25rem 0.6rem;
      border-radius: 999px;
      background: var(--surface-muted);
      color: var(--text-body);
      font-size: 0.82rem;
      font-weight: 600;
    }

    .source-chip.auto {
      background: var(--info-soft);
      color: var(--info);
    }

    @media (max-width: 1100px) {
      .summary-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
    }

    @media (max-width: 900px) {
      .form-grid {
        grid-template-columns: 1fr;
      }

      .item-row {
        grid-template-columns: 1fr;
      }
    }

    @media (max-width: 768px) {
      .page-container {
        padding: 1rem;
      }

      .page-header {
        flex-direction: column;
        align-items: stretch;
      }

      .header-actions,
      .form-actions {
        flex-direction: column;
      }

      .summary-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class InvoicesComponent implements OnInit, OnDestroy {
  allInvoices: Invoice[] = [];
  isLoading = true;
  isFormOpen = false;
  isEditMode = false;
  submittingForm = false;
  editingInvoiceId: number | null = null;
  statusFilter = '';
  errorMessage = '';
  successMessage = '';
  actionMessage = '';
  private refreshHandle: ReturnType<typeof setInterval> | null = null;

  invoiceForm: FormGroup;

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private fb: FormBuilder,
    private http: HttpClient
  ) {
    this.invoiceForm = this.fb.group({
      customerId: [null, [Validators.required, Validators.min(1)]],
      serviceRequestId: [null, [Validators.required, Validators.min(1)]],
      invoiceDate: [''],
      status: ['Pending', Validators.required],
      taxRate: [0.18, [Validators.required, Validators.min(0)]],
      items: this.fb.array([this.createItemGroup()])
    });
  }

  get itemControls(): FormGroup[] {
    return this.items.controls as FormGroup[];
  }

  get showActionsColumn(): boolean {
    return this.authService.hasPermission('Invoices', 'Update')
      || this.authService.hasPermission('Invoices', 'Delete')
      || this.authService.hasPermission('Invoices', 'Export');
  }

  get visibleInvoices(): Invoice[] {
    if (!this.statusFilter) {
      return this.allInvoices;
    }

    return this.allInvoices.filter(invoice => invoice.status === this.statusFilter);
  }

  get autoGeneratedCount(): number {
    return this.allInvoices.filter(invoice => invoice.autoGenerated).length;
  }

  get totalOutstanding(): number {
    return this.allInvoices.reduce((total, invoice) => total + this.getOutstandingAmount(invoice), 0);
  }

  private get items(): FormArray {
    return this.invoiceForm.get('items') as FormArray;
  }

  ngOnInit(): void {
    this.loadInvoices();
    this.refreshHandle = setInterval(() => this.loadInvoices(true), 15000);
  }

  ngOnDestroy(): void {
    if (this.refreshHandle) {
      clearInterval(this.refreshHandle);
      this.refreshHandle = null;
    }
  }

  openCreateForm(): void {
    if (!this.authService.hasPermission('Invoices', 'Create')) {
      this.errorMessage = 'You do not have permission to create invoices.';
      return;
    }

    this.isFormOpen = true;
    this.isEditMode = false;
    this.editingInvoiceId = null;
    this.resetForm();
    this.actionMessage = 'Enter invoice details and save to create a new record.';
    this.errorMessage = '';
    this.successMessage = '';
  }

  editInvoice(invoice: Invoice): void {
    if (!this.authService.hasPermission('Invoices', 'Update')) {
      this.errorMessage = 'You do not have permission to update invoices.';
      return;
    }

    this.apiService.get<Invoice>(`invoices/${invoice.id}`).subscribe({
      next: detailedInvoice => {
        this.isFormOpen = true;
        this.isEditMode = true;
        this.editingInvoiceId = invoice.id;
        this.patchForm(this.normalizeInvoice(detailedInvoice));
        this.actionMessage = `Editing ${invoice.invoiceNo}.`;
        this.errorMessage = '';
        this.successMessage = '';
      },
      error: () => {
        this.errorMessage = 'Invoice details could not be loaded.';
      }
    });
  }

  closeForm(): void {
    this.isFormOpen = false;
    this.isEditMode = false;
    this.editingInvoiceId = null;
    this.submittingForm = false;
    this.resetForm();
  }

  addItem(): void {
    this.items.push(this.createItemGroup());
  }

  removeItem(index: number): void {
    if (this.items.length === 1) {
      return;
    }

    this.items.removeAt(index);
  }

  saveInvoice(): void {
    if (this.invoiceForm.invalid) {
      this.invoiceForm.markAllAsTouched();
      this.errorMessage = 'Please complete all required invoice fields.';
      return;
    }

    const rawValue = this.invoiceForm.getRawValue();
    const payloadItems = (rawValue.items as InvoiceItemRequest[]).map(item => ({
      itemName: `${item.itemName ?? ''}`.trim(),
      quantity: Number(item.quantity),
      unitPrice: Number(item.unitPrice)
    }));

    this.submittingForm = true;
    this.errorMessage = '';
    this.successMessage = '';

    if (this.isEditMode && this.editingInvoiceId) {
      this.apiService.put<Invoice>(`invoices/${this.editingInvoiceId}`, {
        status: rawValue.status,
        items: payloadItems,
        taxRate: Number(rawValue.taxRate)
      }).pipe(
        finalize(() => {
          this.submittingForm = false;
        })
      ).subscribe({
        next: updatedInvoice => {
          this.replaceInvoice(updatedInvoice);
          this.successMessage = `${updatedInvoice.invoiceNo} updated successfully.`;
          this.actionMessage = '';
          this.closeForm();
        },
        error: () => {
          this.errorMessage = 'Invoice could not be updated right now.';
        }
      });

      return;
    }

    const createPayload: InvoiceCreateRequest = {
      customerId: Number(rawValue.customerId),
      serviceRequestId: Number(rawValue.serviceRequestId),
      invoiceDate: rawValue.invoiceDate ? new Date(rawValue.invoiceDate) : undefined,
      taxRate: Number(rawValue.taxRate),
      items: payloadItems
    };

    this.apiService.post<Invoice>('invoices', createPayload).pipe(
      finalize(() => {
        this.submittingForm = false;
      })
    ).subscribe({
      next: createdInvoice => {
        this.allInvoices = [this.normalizeInvoice(createdInvoice), ...this.allInvoices];
        this.successMessage = `${createdInvoice.invoiceNo} created successfully.`;
        this.actionMessage = '';
        this.closeForm();
      },
      error: () => {
        this.errorMessage = 'Invoice could not be created right now.';
      }
    });
  }

  deleteInvoice(invoice: Invoice): void {
    if (!this.authService.hasPermission('Invoices', 'Delete')) {
      this.errorMessage = 'You do not have permission to delete invoices.';
      return;
    }

    if (!confirm(`Delete ${invoice.invoiceNo}?`)) {
      return;
    }

    this.apiService.delete<{ deleted: boolean }>(`invoices/${invoice.id}`).subscribe({
      next: () => {
        this.allInvoices = this.allInvoices.filter(existingInvoice => existingInvoice.id !== invoice.id);
        this.successMessage = `${invoice.invoiceNo} was removed successfully.`;
      },
      error: () => {
        this.errorMessage = 'Invoice could not be deleted right now.';
      }
    });
  }

  exportInvoice(invoice: Invoice): void {
    if (!this.authService.hasPermission('Invoices', 'Export')) {
      this.errorMessage = 'You do not have permission to export invoices.';
      return;
    }

    this.http.get(`${environment.apiUrl}/invoices/${invoice.id}/pdf`, {
      responseType: 'blob'
    }).subscribe({
      next: blob => {
        const objectUrl = URL.createObjectURL(blob);
        const anchor = document.createElement('a');
        anchor.href = objectUrl;
        anchor.download = `${invoice.invoiceNo}.pdf`;
        anchor.click();
        URL.revokeObjectURL(objectUrl);
      },
      error: () => {
        this.errorMessage = 'Invoice export could not be generated right now.';
      }
    });
  }

  loadInvoices(backgroundRefresh = false): void {
    if (!backgroundRefresh) {
      this.isLoading = true;
    }

    this.errorMessage = backgroundRefresh ? this.errorMessage : '';

    this.apiService.get<PagedResponse<Invoice>>('invoices', {
      page: '1',
      pageSize: '250'
    }).subscribe({
      next: response => {
        this.allInvoices = response.items
          .map(invoice => this.normalizeInvoice(invoice))
          .sort((left, right) => right.invoiceDate.getTime() - left.invoiceDate.getTime());
        this.isLoading = false;
      },
      error: () => {
        this.errorMessage = 'Invoices could not be loaded right now.';
        this.isLoading = false;
      }
    });
  }

  countByStatus(status: InvoiceStatus): number {
    return this.allInvoices.filter(invoice => invoice.status === status).length;
  }

  getOutstandingAmount(invoice: Invoice): number {
    if (typeof invoice.outstandingAmount === 'number') {
      return invoice.outstandingAmount;
    }

    if (typeof invoice.paidAmount === 'number') {
      return Math.max(invoice.totalAmount - invoice.paidAmount, 0);
    }

    if (invoice.status === 'Paid') {
      return 0;
    }

    return invoice.totalAmount;
  }

  private patchForm(invoice: Invoice): void {
    this.invoiceForm.patchValue({
      customerId: invoice.customerId,
      serviceRequestId: invoice.serviceRequestId,
      invoiceDate: this.formatDateInput(invoice.invoiceDate),
      status: invoice.status === 'Overdue'
        ? ((invoice.paidAmount ?? 0) > 0 ? 'Partial' : 'Pending')
        : invoice.status,
      taxRate: invoice.taxRate ?? 0
    });

    this.items.clear();
    const items = invoice.items?.length ? invoice.items : [{ itemName: 'Invoice item', quantity: 1, unitPrice: invoice.totalAmount }];
    items.forEach(item => {
      this.items.push(this.createItemGroup(item));
    });
  }

  private resetForm(): void {
    this.invoiceForm.reset({
      customerId: null,
      serviceRequestId: null,
      invoiceDate: this.formatDateInput(new Date()),
      status: 'Pending',
      taxRate: 0.18
    });

    this.items.clear();
    this.items.push(this.createItemGroup());
  }

  private createItemGroup(item?: Partial<InvoiceItem>): FormGroup {
    return this.fb.group({
      itemName: [item?.itemName ?? '', Validators.required],
      quantity: [item?.quantity ?? 1, [Validators.required, Validators.min(1)]],
      unitPrice: [item?.unitPrice ?? 0, [Validators.required, Validators.min(0)]]
    });
  }

  private normalizeInvoice(invoice: Invoice): Invoice {
    const invoiceDate = invoice.invoiceDate ? new Date(invoice.invoiceDate) : new Date();
    const paidAmount = typeof invoice.paidAmount === 'number'
      ? invoice.paidAmount
      : (invoice.status === 'Paid' ? invoice.totalAmount : 0);
    const outstandingAmount = typeof invoice.outstandingAmount === 'number'
      ? invoice.outstandingAmount
      : Math.max(invoice.totalAmount - paidAmount, 0);

    return {
      ...invoice,
      invoiceDate,
      paidAmount,
      outstandingAmount,
      status: this.deriveStatus(invoice.status, invoiceDate),
      items: invoice.items?.map(item => ({
        ...item,
        totalPrice: item.totalPrice ?? (item.quantity * item.unitPrice)
      }))
    };
  }

  private replaceInvoice(invoice: Invoice): void {
    const normalizedInvoice = this.normalizeInvoice(invoice);
    this.allInvoices = this.allInvoices.map(existingInvoice =>
      existingInvoice.id === normalizedInvoice.id ? normalizedInvoice : existingInvoice
    );
  }

  private deriveStatus(status: InvoiceStatus, invoiceDate: Date): InvoiceStatus {
    if ((status === 'Pending' || status === 'Partial') && this.isOlderThanDays(invoiceDate, 7)) {
      return 'Overdue';
    }

    return status;
  }

  private isOlderThanDays(date: Date, days: number): boolean {
    const threshold = new Date();
    threshold.setDate(threshold.getDate() - days);
    return date.getTime() < threshold.getTime();
  }

  private formatDateInput(value: Date | string | undefined): string {
    const date = value ? new Date(value) : new Date();
    const year = date.getFullYear();
    const month = `${date.getMonth() + 1}`.padStart(2, '0');
    const day = `${date.getDate()}`.padStart(2, '0');
    return `${year}-${month}-${day}`;
  }
}
